// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfxfyvfbyaomajudimds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmeGZ5dmZieWFvbWFqdWRpbWRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2ODk3ODUsImV4cCI6MjA2NzI2NTc4NX0.So4e3FSvHwy0ED56PMQcLsvRieK8K7FcyFYmSOI_-t8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});